var guestArray = ["ali", "noman", "zain"];
var canNotAttend = "noman";
var newGuest = "muhammad";
guestArray[guestArray.indexOf(canNotAttend)] = newGuest;
guestArray.map(function (items) { return console.log("Hello,".concat(items, "you are invited to dinner")); });
console.log("We found a bigger dinner table!");
guestArray.unshift("ahmed");
console.log(guestArray);
var middleGuest = "rashid";
var middleIndex = guestArray.length / 2;
guestArray.splice(middleIndex, 0, middleGuest);
console.log(guestArray);
guestArray.push("muhammad");
console.log(guestArray);
guestArray.map(function (items) { return console.log("\nDear ".concat(items, " You are invited to dinner!")); });
